[tox]
envlist = py311
skip_missing_interpreters = true

[testenv]
package = skip
passenv =
    PATH
deps =
    -r requirements.txt
commands = 
	pytest gmsm/tests --basetemp={envtmpdir}{/}pytest -p no:cacheprovider -v \
	--cov=gmsm --cov-report term-missing
	
[pytest]
addopts = -p no:warnings
