[tox]
envlist = py311
skip_missing_interpreters = true

[testenv]
package = skip
deps =
    -r requirements.txt
commands = 
	pytest gmsm/tests --basetemp={envtmpdir}/pytest -p no:cacheprovider -v \
	--cov=gmsm/config --cov=gmsm/homology --cov=gmsm/io --cov=gmsm/primary_model \
	--cov=gmsm/secondary_model --cov=gmsm.utils --cov-report term-missing
	
[pytest]
addopts = -p no:warnings
